---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pjjknet/public_html/BAIA
    - /bin/cp beowulf.ttl $DEPLOYPATH
    - /bin/cp beowulf.xml $DEPLOYPATH
    - /bin/cp entities.ttl $DEPLOYPATH
    - /bin/cp ontology.ttl $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
